### ISSUE TITLE
How to Generate lbs_map_smpl_512.npy for Other Template Models

### ISSUE THREAD

**Issue by ZhaoLizz** [aipixel/GaussianAvatar#23]
Hi! 
Are there specific tools or scripts available that can help in generating an LBS map for models other than the SMPL and SMPL-X models?  
It seems the LBS map indicates corresponding valid vertex skinning weights, and here we need the vertex id map to generate the LBS map. 
But the render_posmap function only returns face ids, rather than the vertex ids. How should I get the vertex id map? Or are there any scripts to generate the LBS map directly from model uvs?
Thank you for your time and assistance.

**Comment by huliangxiao** [comment]
Please refer to this issue (https://github.com/aipixel/GaussianAvatar/issues/21#issuecomment-1982246243)

**Comment by ZhaoLizz** [comment]
Thanks for your help!
